### ISSUE TITLE
Editor does not draw new points at cursor on Mac

### ISSUE THREAD

**Issue by louy2** [phaazon/spline-editor#2]
Code at [main:126](https://github.com/phaazon/spline-editor/blob/b852d97445d369463f61e74251750671bf8a0a88/src/main.rs#L126) draws a point at halfway between top-left corner and cursor on Macbook Pro with macOS Mojave on a 2560x1600 screen. `2. * x` and `4. * y` draws a point at cursor but not sure how to do this cross platform. I guess HiDPI is just hard.

**Comment by phaazon** [comment]
Haha, I think I know why. Thanks for reporting, I’ll fix it.

**Comment by phaazon** [comment]
Maybe `luminance-glfw` needs a fix about that, because here, if we redimension the window, we’re a bit screwed.
